### ISSUE TITLE
No X11 DISPLAY variable was set, or no headful library support was found

### ISSUE THREAD

**Issue by DadiBit** [QuentiumYT/jd-gui#1]
When trying to run the app I get the following error:
```
$ java -jar jd-gui-1.7.1.jar 
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:186)
	at org.jd.gui.service.configuration.ConfigurationXmlPersisterProvider.load(ConfigurationXmlPersisterProvider.java:71)
	at org.jd.gui.App.main(App.java:34)
```

**Comment by DadiBit** [comment]
The solution was installing a non headless jdk (Fedora 41 comes with openjdk 21 headless preinstalled)

We should update docs to set build/run requirements to non headless versions :)

**Comment by DadiBit** [comment]
The solution was installing a non headless jdk (Fedora 41 comes with openjdk 21 headless preinstalled)

We should update docs to set build/run requirements to non headless versions :)
